/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateTeacherArgs } from "./CreateTeacherArgs";
import { UpdateTeacherArgs } from "./UpdateTeacherArgs";
import { DeleteTeacherArgs } from "./DeleteTeacherArgs";
import { TeacherFindManyArgs } from "./TeacherFindManyArgs";
import { TeacherFindUniqueArgs } from "./TeacherFindUniqueArgs";
import { Teacher } from "./Teacher";
import { TestFindManyArgs } from "../../test/base/TestFindManyArgs";
import { Test } from "../../test/base/Test";
import { TeacherService } from "../teacher.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Teacher)
export class TeacherResolverBase {
  constructor(
    protected readonly service: TeacherService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Teacher",
    action: "read",
    possession: "any",
  })
  async _teachersMeta(
    @graphql.Args() args: TeacherFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Teacher])
  @nestAccessControl.UseRoles({
    resource: "Teacher",
    action: "read",
    possession: "any",
  })
  async teachers(
    @graphql.Args() args: TeacherFindManyArgs
  ): Promise<Teacher[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Teacher, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Teacher",
    action: "read",
    possession: "own",
  })
  async teacher(
    @graphql.Args() args: TeacherFindUniqueArgs
  ): Promise<Teacher | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Teacher)
  @nestAccessControl.UseRoles({
    resource: "Teacher",
    action: "create",
    possession: "any",
  })
  async createTeacher(
    @graphql.Args() args: CreateTeacherArgs
  ): Promise<Teacher> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Teacher)
  @nestAccessControl.UseRoles({
    resource: "Teacher",
    action: "update",
    possession: "any",
  })
  async updateTeacher(
    @graphql.Args() args: UpdateTeacherArgs
  ): Promise<Teacher | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Teacher)
  @nestAccessControl.UseRoles({
    resource: "Teacher",
    action: "delete",
    possession: "any",
  })
  async deleteTeacher(
    @graphql.Args() args: DeleteTeacherArgs
  ): Promise<Teacher | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Test])
  @nestAccessControl.UseRoles({
    resource: "Test",
    action: "read",
    possession: "any",
  })
  async test(
    @graphql.Parent() parent: Teacher,
    @graphql.Args() args: TestFindManyArgs
  ): Promise<Test[]> {
    const results = await this.service.findTest(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
